### ISSUE TITLE
Decide Technologies for Data Analysis

### ISSUE THREAD

**Issue by juanjuanjuanfer** [juanjuanjuanfer/fars#1]
Select the technologies to be used for the Data Analysis part.

FRONTEND FRAMEWORK | CAMERA INTEGRATION | ATTENDANCE UI | REPORT MAKING

Please use the Google Sheets Morphological Box previously provided

**Comment by ChrisCL1** [comment]
Completed
Frontend Framework: Streamlit/Dash.
Camera Integration: OpenCV.
Registration UI: Real-time video and samples extraction.
Attendance UI: Real-time video feed.
Report Making: Pandas/Plotly.
