### ISSUE TITLE
Create the assistance report structure and make a mockup

### ISSUE THREAD

**Issue by juanjuanjuanfer** [juanjuanjuanfer/fars#10]
**Description**: Define the structure of the attendance report and create a mockup of how it will be displayed in the app.

**Comment by ChrisCL1** [comment]
### Structure for the Interface - Version 1

**Attendance Interface**

Elements:
- Live Video Feed Box:
  - An area displaying the live camera feed.
  - Facial detection indicator (box drawn around detected face).
- Start Camera Button:
  - Primary button to activate the camera and start the facial recognition process.
  - Button text: "Start Camera"
- Status Indicator:
  - A message that displays when the system detects a face and marks attendance.
  - Message: "Attendance Registered for [Student Name]
- Manual Attendance Button:
  - Option to manually record attendance if the system fails to recognize a face or in case of technical issues.
  - Button text: "Record Manual Attendance"
- Manual Attendance Menu:
  - A field to write manually the student name.
  
**Student Registration Interface**

Elements:
- Input Form:
  - Text Field for Full Name:
    - Label: "Full Name of Student"
    - Text input where the user can type the student's name.
  - Text Field for Student ID:
    - Label:  "Student ID"
    - Text input for the student's unique ID.
- Video Capture:
  - Option to record a video that captures various angles of the student's face.
  - Label: "Record Video"
- Video Preview:
  - Area to display a preview of the video.
- Frame Extraction:
  - An automatic process that occurs after the video is recorded and saved.
  - A visual indicator informs the user that the system is extracting several frames from the video.
- Image Frames Preview:
  - Display a series of images that were extracted from the video.
  - Option to delete any frame that is inadequate.
- Save Student Button:
  - A button that confirms and saves the student's data along with the extracted images.
  - Button text: "Save Student"
- Registered Student Table:
  - A list of all the students who have already been registered in the system.
  - Columns: Name, Student ID.
  - Option to edit or delete records as needed.

**Attendance Report Interface**

Elements:
- Attendance Table:
  - Displays the attendance records of students.
  - Columns: Student Name, Days "Present", Days "Absent", Days "Late".
  - Data can be filtered by date or groups/classes.
- Bar Chart (Attendance Comparison by Student) :
  - A bar chart that compares attendance among students.
  - X-Axis: Student Names.
  - Y-Axis: Days of Attendance (Present, Absent, Late).
  - Bars grouped by each attendance state.
- Pie Chart (Attendance Proportion) :
  - A pie chart showing the proportion of days students were present, absent, or late.
  - Three categories: "Present", "Absent", "Late".
  - Displays the percentage for each attendance state.
- Export Report Button:
  - A button that allows users to download the attendance report in Excel or PDF format.
  - Button text: "Download Attendance Report".
- Date Range Selector:
  - A filter allowing users to select a date range for generating a specific report.
  - Label: "Select Date Range."

**Comment by ChrisCL1** [comment]
Report Structure:

- Student Name
- Student ID
- Dates (Date of the Lesson)
- Present (Number of Attendances "P")
- Absent (Number of Absences "A")
- Late (Number of late arrivals "L")
- Justified Absence
- Percentage (Percentage of attendances for the entire period)
 
![Image](https://github.com/user-attachments/assets/eeaa22db-72b6-4cf4-b7fc-3046bb94de70)
