### ISSUE TITLE
Create mockups for the web app

### ISSUE THREAD

**Issue by juanjuanjuanfer** [juanjuanjuanfer/fars#8]
**Description**: Design mockups for all the web pages to be used in the application. Ensure the mockups include all required features such as login, image capture, and reports.

**Comment by ChrisCL1** [comment]
![Image](https://github.com/user-attachments/assets/b6f4e000-e078-442e-a276-54beee0a0973)
![Image](https://github.com/user-attachments/assets/89acc2f1-c306-495c-9750-d8b4cf3d542b)
![Image](https://github.com/user-attachments/assets/472ea4e9-1307-4360-b85d-170d2445e15c)
![Image](https://github.com/user-attachments/assets/c6264448-c4d4-4a62-b30c-5959f4b3fddb)
![Image](https://github.com/user-attachments/assets/2b45dbb9-e805-4219-9412-4b5a509d206c)
![Image](https://github.com/user-attachments/assets/c655efb2-6f96-4b7e-9bac-c2c4a5b5e46c)
